# Generated by Django 5.1 on 2024-12-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('tipo_producto', models.CharField(max_length=45)),
                ('lote', models.IntegerField()),
                ('marca', models.CharField(max_length=60)),
                ('id_sucursal', models.CharField(max_length=6)),
            ],
        ),
    ]
