# Generated by Django 5.1 on 2024-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField(max_length=11)),
                ('tipo_producto', models.CharField(max_length=45)),
                ('lote', models.IntegerField(max_length=15)),
                ('marca', models.IntegerField(max_length=6)),
            ],
        ),
    ]
