# Generated by Django 5.1 on 2024-11-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoP', models.CharField(max_length=45)),
                ('apellidoM', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=20)),
                ('cuenta', models.CharField(max_length=20)),
            ],
        ),
    ]
