# Generated by Django 5.1 on 2024-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('Id_Sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sucursale',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'Sucursales',
            },
        ),
    ]
